name: XeonSuiteHome
version: ${project.version}.b${build.number}
description: Homeplugin
authors: [Kekshaus]
main: de.nlinz.xeonSuite.home.Homeplugin
load: POSTWORLD
depend: [XeonSuiteBukkit]

commands:
  sethome:
    description: Set your home.
  home:
    description: Teleport back to your set home.
  homes:
    description: Get Homelist.
  delhome:
    description: Delete a home

permissions:
    xeonSuite.home.team:
        description: Alle Permissions
        children:
            xeonSuite.home.limit.admin: true
            xeonSuite.home.user: true
    xeonSuite.home.user:
        description: Alle User Permissions
        children:
            xeonSuite.home.home: true
            xeonSuite.home.sethome: true
            xeonSuite.home.homes: true
            xeonSuite.home.delhome: true
    xeonSuite.home.home:
        description: Teleport to home
        default: op
    xeonSuite.home.sethome:
        description: Teleport to home
        default: op
    xeonSuite.home.homes:
        description: Teleport to home
        default: op
    xeonSuite.home.delhome:
        description: Teleport to home
        default: op
    xeonSuite.home.limit.admin:
        description: Homes limit
        default: op
    xeonSuite.home.limit.2:
        description: Homes limit
        default: op
    xeonSuite.home.limit.3:
        description: Homes limit
        default: op
    xeonSuite.home.limit.4:
        description: Homes limit
        default: op
    xeonSuite.home.limit.5:
        description: Homes limit
        default: op
    xeonSuite.home.limit.6:
        description: Homes limit
        default: op
    xeonSuite.home.limit.7:
        description: Homes limit
        default: op
    xeonSuite.home.limit.8:
        description: Homes limit
        default: op
    xeonSuite.home.limit.9:
        description: Homes limit
        default: op