name: MineSuiteHome
version: ${project.version}
description: Home module for MineSuiteCore
authors: [Kekshaus]
main: de.linzn.mineSuite.home.HomePlugin
load: POSTWORLD
depend: [MineSuiteCore]
api-version: 1.13
commands:
  sethome:
    description: Set your home.
  home:
    description: Teleport back to your set home.
  homes:
    description: Get Homelist.
  delhome:
    description: Delete a home

permissions:
    mineSuite.home.team:
        description: Alle Permissions
        children:
            mineSuite.home.limit.admin: true
            mineSuite.home.user: true
    mineSuite.home.user:
        description: Alle User Permissions
        children:
            mineSuite.home.home: true
            mineSuite.home.sethome: true
            mineSuite.home.homes: true
            mineSuite.home.delhome: true
    mineSuite.home.home:
        description: Teleport to home
        default: op
    mineSuite.home.sethome:
        description: Teleport to home
        default: op
    mineSuite.home.homes:
        description: Teleport to home
        default: op
    mineSuite.home.delhome:
        description: Teleport to home
        default: op
    mineSuite.home.limit.admin:
        description: Homes limit
        default: op
    mineSuite.home.limit.2:
        description: Homes limit
        default: op
    mineSuite.home.limit.3:
        description: Homes limit
        default: op
    mineSuite.home.limit.4:
        description: Homes limit
        default: op
    mineSuite.home.limit.5:
        description: Homes limit
        default: op
    mineSuite.home.limit.6:
        description: Homes limit
        default: op
    mineSuite.home.limit.7:
        description: Homes limit
        default: op
    mineSuite.home.limit.8:
        description: Homes limit
        default: op
    mineSuite.home.limit.9:
        description: Homes limit
        default: op